### ISSUE TITLE
Add more hostnames.

### ISSUE THREAD

**Issue by EnterGin** [loomkoom/get-vods-clips#1]
Gogi 7 :)

There are more hostnames for VODs. For example: https://twitchtracker.com/robcdee/streams/40296800364
Link for this VOD: ```https://d3c27h4odz752x.cloudfront.net/5dc51688c89beb5a1369_robcdee_40296800364_1607578423/chunked/index-dvr.m3u8```
There are 3 hostnames:
```vod-secure.twitch.tv```, ```d2nvs31859zcd8.cloudfront.net```, ```d3c27h4odz752x.cloudfront.net```
You can also use HEAD request to check which link is correct.

**Comment by loomkoom** [comment]
Sure I could add a check for multiple hosts.
what would be the reason though? from what I could tell all of them are accessible via `vod-secure.twitch.tv` so checking multiple would just add more time (as I actually try to play them to make sure the link is valid)
I'll look into it tomorrow

**Comment by EnterGin** [comment]
Reason: not all VODs stored on vod-secure hostname. Trying to play stream is a bad idea to be honest. Better to do HEAD request.

**Comment by loomkoom** [comment]
Allright I'll add it.
And I do a head request and play afterwards. 
Seemed the easiest way to get around links that gave a 200 response but weren't actually able to play.
I made it an argument though, so if you're fine with some more false positives you can just disable the play test option.

**Comment by EnterGin** [comment]
Good scripts tho, nice work. 
👽 7 🥩7

**Comment by loomkoom** [comment]
3ecc3976feabb0321d20675e4afb8def6cdf78ef added, it will return the first host from the list. I'll manually add more hosts if I see a new one.
